const express = require('express');
const router = express.Router();
var nodemailer = require('nodemailer');

/*---------------------------
| Nodemailer Initialized
---------------------------*/
var transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: process.env.EMAIL_PORT,
    auth: {
        user: process.env.EMAIL_USER, //generated by Mailtrap
        pass: process.env.EMAIL_PASS //generated by Mailtrap
    },
    debug: (process.env.EMAIL_DEBUG === 'true'), // show debug output
    logger: (process.env.EMAIL_DEBUG === 'true') // log information in console
});

/*---------------------------
| Route Handler for Emailing.
---------------------------*/
router.post('/send', (req, res) => {
    const response = {
        errors: false,
        message: 'Email Sent',
        postedData: req.body,
    }

    var mailOptions = {
        from: process.env.EMAIL_FROM,
        to: process.env.EMAIL_RECIP,
        subject: 'Sending Email using Node.js',
        html: '<p>Hey Mitch,</p><p>Someone is contacting you.</p>'
    };

    transporter.sendMail(mailOptions, function (error, info) {
        if (error) {
            console.log(error);
        } else {
            console.log('Email sent: ' + info.response);
        }
    });



    console.log('Post Sent Email');
    res.json(response);
});

module.exports = router;