/*===================================
|| 
|| Email API Handler
|| 
===================================*/
/*---------------------------
| Strip Tags
---------------------------*/
const stripHtml = require("string-strip-html");

/*---------------------------
| Nodemailer Initialized
---------------------------*/
var nodemailer = require('nodemailer');
var transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: process.env.EMAIL_PORT,
    auth: {
        user: process.env.EMAIL_USER, //generated by Mailtrap
        pass: process.env.EMAIL_PASS //generated by Mailtrap
    },
    debug: (process.env.EMAIL_DEBUG === 'true'), // show debug output
    logger: (process.env.EMAIL_DEBUG === 'true') // log information in console
});


/*---------------------------
| SendGrid
---------------------------*/
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

/*---------------------------
| Send Email
---------------------------*/
const EmailAPI = (replyTo, messageBody) => {

    const composeHTML = (msgBody) => {
        return `
            <p>Hello ${process.env.EMAIL_NAME},</p>

            ${msgBody}

            <p>
                Love,<br />
                Hubby
            </p>
        `;
    };

    console.log('process.env', process.env);

    const message = {
        to: process.env.EMAIL_RECIP,
        from: process.env.EMAIL_FROM,
        replyTo: replyTo,
        subject: 'Someone is sending your email from ' + process.env.REACT_APP_DOMAIN,
        text: stripHtml(messageBody),
        html: composeHTML(messageBody),
    }

    const sendEmail = () => {
        /* Mailtrap ---------------------------*/
        if (process.env.EMAIL_API === 'mailtrap') {
            
            console.log('Email API: Mailtrap');

            transporter.sendMail(message, function (error, info) {
                if (error) {
                    console.log(error);
                } else {
                    console.log('Email sent: ' + info.response);
                }
            });
            return true;
        } 

        /* SendGrid ---------------------------*/
        console.log('Email API: SendGrid');

        sgMail.send(message).then((resp) => {
            console.log('Message sent', resp)
        }).catch((error) => {
            // console.log(error.response.body);
            console.log(error);
        });
    }

    return {
        send: sendEmail
    }

}

module.exports = EmailAPI;